DROP TABLE IF EXISTS covid_data;

CREATE TABLE covid_data (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    population BIGINT NULL,
    total_cases BIGINT NULL,
    new_cases BIGINT NULL,
    new_cases_smoothed DOUBLE NULL,
    total_deaths BIGINT NULL,
    new_deaths BIGINT NULL,
    new_deaths_smoothed DOUBLE NULL,
    total_cases_per_million DOUBLE NULL,
    new_cases_per_million DOUBLE NULL,
    new_cases_smoothed_per_million DOUBLE NULL,
    total_deaths_per_million DOUBLE NULL,
    new_deaths_per_million DOUBLE NULL,
    new_deaths_smoothed_per_million DOUBLE NULL,
    reproduction_rate DOUBLE NULL,
    icu_patients BIGINT NULL,
    icu_patients_per_million DOUBLE NULL,
    hosp_patients BIGINT NULL,
    hosp_patients_per_million DOUBLE NULL,
    weekly_icu_admissions BIGINT NULL,
    weekly_icu_admissions_per_million DOUBLE NULL,
    weekly_hosp_admissions BIGINT NULL,
    weekly_hosp_admissions_per_million DOUBLE NULL,
    new_tests BIGINT NULL,
    total_tests BIGINT NULL,
    total_tests_per_thousand DOUBLE NULL,
    new_tests_per_thousand DOUBLE NULL,
    new_tests_smoothed BIGINT NULL,
    new_tests_smoothed_per_thousand DOUBLE NULL,
    positive_rate DOUBLE NULL,
    tests_per_case DOUBLE NULL,
    tests_units VARCHAR(50),
    total_vaccinations BIGINT NULL,
    people_vaccinated BIGINT NULL,
    people_fully_vaccinated BIGINT NULL,
    new_vaccinations BIGINT NULL,
    new_vaccinations_smoothed BIGINT NULL,
    total_vaccinations_per_hundred DOUBLE NULL,
    people_vaccinated_per_hundred DOUBLE NULL,
    people_fully_vaccinated_per_hundred DOUBLE NULL,
    new_vaccinations_smoothed_per_million DOUBLE NULL,
    stringency_index DOUBLE NULL,
    population_density DOUBLE NULL,
    median_age DOUBLE NULL,
    aged_65_older DOUBLE NULL,
    aged_70_older DOUBLE NULL,
    gdp_per_capita DOUBLE NULL,
    extreme_poverty DOUBLE NULL,
    cardiovasc_death_rate DOUBLE NULL,
    diabetes_prevalence DOUBLE NULL,
    female_smokers DOUBLE NULL,
    male_smokers DOUBLE NULL,
    handwashing_facilities DOUBLE NULL,
    hospital_beds_per_thousand DOUBLE NULL,
    life_expectancy DOUBLE NULL,
    human_development_index DOUBLE NULL
);

LOAD DATA LOCAL INFILE "C:/Users/simid/Desktop/PROJECTS/Covid Deaths/Covid-dataset.csv" 
INTO TABLE covid_data 
FIELDS TERMINATED BY ','  
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n' -- Fixes the line-ending warnings on Windows
IGNORE 1 LINES 
( 
    iso_code, continent, location, date, 
    @population, @total_cases, @new_cases, @new_cases_smoothed, 
    @total_deaths, @new_deaths, @new_deaths_smoothed, 
    @total_cases_per_million, @new_cases_per_million, @new_cases_smoothed_per_million, 
    @total_deaths_per_million, @new_deaths_per_million, @new_deaths_smoothed_per_million, 
    @reproduction_rate, @icu_patients, @icu_patients_per_million, 
    @hosp_patients, @hosp_patients_per_million, @weekly_icu_admissions, 
    @weekly_icu_admissions_per_million, @weekly_hosp_admissions, @weekly_hosp_admissions_per_million, 
    @new_tests, @total_tests, @total_tests_per_thousand, @new_tests_per_thousand, 
    @new_tests_smoothed, @new_tests_smoothed_per_thousand, @positive_rate, @tests_per_case, 
    tests_units, @total_vaccinations, @people_vaccinated, @people_fully_vaccinated, 
    @new_vaccinations, @new_vaccinations_smoothed, @total_vaccinations_per_hundred, 
    @people_vaccinated_per_hundred, @people_fully_vaccinated_per_hundred, 
    @new_vaccinations_smoothed_per_million, @stringency_index, @population_density, 
    @median_age, @aged_65_older, @aged_70_older, @gdp_per_capita, @extreme_poverty, 
    @cardiovasc_death_rate, @diabetes_prevalence, @female_smokers, @male_smokers, 
    @handwashing_facilities, @hospital_beds_per_thousand, @life_expectancy, @human_development_index 
) 
SET  
    population = NULLIF(@population, ''),
    total_cases = NULLIF(@total_cases, ''),
    new_cases = NULLIF(@new_cases, ''),
    new_cases_smoothed = NULLIF(@new_cases_smoothed, ''),
    total_deaths = NULLIF(@total_deaths, ''),
    new_deaths = NULLIF(@new_deaths, ''),
    new_deaths_smoothed = NULLIF(@new_deaths_smoothed, ''),
    total_cases_per_million = NULLIF(@total_cases_per_million, ''),
    new_cases_per_million = NULLIF(@new_cases_per_million, ''),
    new_cases_smoothed_per_million = NULLIF(@new_cases_smoothed_per_million, ''),
    total_deaths_per_million = NULLIF(@total_deaths_per_million, ''),
    new_deaths_per_million = NULLIF(@new_deaths_per_million, ''),
    new_deaths_smoothed_per_million = NULLIF(@new_deaths_smoothed_per_million, ''),
    reproduction_rate = NULLIF(@reproduction_rate, ''),
    icu_patients = NULLIF(@icu_patients, ''),
    icu_patients_per_million = NULLIF(@icu_patients_per_million, ''),
    hosp_patients = NULLIF(@hosp_patients, ''),
    hosp_patients_per_million = NULLIF(@hosp_patients_per_million, ''),
    weekly_icu_admissions = NULLIF(@weekly_icu_admissions, ''),
    weekly_icu_admissions_per_million = NULLIF(@weekly_icu_admissions_per_million, ''),
    weekly_hosp_admissions = NULLIF(@weekly_hosp_admissions, ''),
    weekly_hosp_admissions_per_million = NULLIF(@weekly_hosp_admissions_per_million, ''),
    new_tests = NULLIF(@new_tests, ''),
    total_tests = NULLIF(@total_tests, ''),
    total_tests_per_thousand = NULLIF(@total_tests_per_thousand, ''),
    new_tests_per_thousand = NULLIF(@new_tests_per_thousand, ''),
    new_tests_smoothed = NULLIF(@new_tests_smoothed, ''),
    new_tests_smoothed_per_thousand = NULLIF(@new_tests_smoothed_per_thousand, ''),
    positive_rate = NULLIF(@positive_rate, ''),
    tests_per_case = NULLIF(@tests_per_case, ''),
    total_vaccinations = NULLIF(@total_vaccinations, ''),
    people_vaccinated = NULLIF(@people_vaccinated, ''),
    people_fully_vaccinated = NULLIF(@people_fully_vaccinated, ''),
    new_vaccinations = NULLIF(@new_vaccinations, ''),
    new_vaccinations_smoothed = NULLIF(@new_vaccinations_smoothed, ''),
    total_vaccinations_per_hundred = NULLIF(@total_vaccinations_per_hundred, ''),
    people_vaccinated_per_hundred = NULLIF(@people_vaccinated_per_hundred, ''),
    people_fully_vaccinated_per_hundred = NULLIF(@people_fully_vaccinated_per_hundred, ''),
    new_vaccinations_smoothed_per_million = NULLIF(@new_vaccinations_smoothed_per_million, ''),
    stringency_index = NULLIF(@stringency_index, ''),
    population_density = NULLIF(@population_density, ''),
    median_age = NULLIF(@median_age, ''),
    aged_65_older = NULLIF(@aged_65_older, ''),
    aged_70_older = NULLIF(@aged_70_older, ''),
    gdp_per_capita = NULLIF(@gdp_per_capita, ''),
    extreme_poverty = NULLIF(@extreme_poverty, ''),
    cardiovasc_death_rate = NULLIF(@cardiovasc_death_rate, ''),
    diabetes_prevalence = NULLIF(@diabetes_prevalence, ''),
    female_smokers = NULLIF(@female_smokers, ''),
    male_smokers = NULLIF(@male_smokers, ''),
    handwashing_facilities = NULLIF(@handwashing_facilities, ''),
    hospital_beds_per_thousand = NULLIF(@hospital_beds_per_thousand, ''),
    life_expectancy = NULLIF(@life_expectancy, ''),
    human_development_index = NULLIF(TRIM(BOTH '\r' FROM @human_development_index), '');